# packages in environment at /home/16ee35016/anaconda2/envs/HSD:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
blas                      1.0                         mkl  
ca-certificates           2020.12.8            h06a4308_0  
certifi                   2020.12.5        py37h06a4308_0  
cffi                      1.14.4           py37h261ae71_0  
cudatoolkit               10.1.243             h6bb024c_0  
cycler                    0.10.0                    <pip>
freetype                  2.10.4               h5ab3b9f_0  
hsd-semantic              1.0                       <pip>
intel-openmp              2020.2                      254  
joblib                    1.0.0                     <pip>
jpeg                      9b                   h024ee3a_2  
kiwisolver                1.3.1                     <pip>
lcms2                     2.11                 h396b838_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_1  
libuv                     1.40.0               h7b6447c_0  
lqnets                    1.0                       <pip>
lz4-c                     1.9.2                heb0550a_3  
matplotlib                3.3.3                     <pip>
mkl                       2020.2                      256  
mkl-service               2.3.0            py37he8ac12f_0  
mkl_fft                   1.2.0            py37h23d657b_0  
mkl_random                1.1.1            py37h0573a6f_0  
ncurses                   6.2                  he6710b0_1  
ninja                     1.10.2           py37hff7bd54_0  
nose                      1.3.7                     <pip>
numpy                     1.19.2           py37h54aff64_0  
numpy-base                1.19.2           py37hfa32c7d_0  
olefile                   0.46                       py_0  
openssl                   1.1.1i               h27cfd23_0  
pillow                    8.0.1            py37he98fc37_0  
pip                       20.3.3           py37h06a4308_0  
pycparser                 2.20                       py_2  
pyparsing                 2.4.7                     <pip>
python                    3.7.9                h7579374_0  
python-dateutil           2.8.1                     <pip>
pytorch                   1.4.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
PyYAML                    5.3.1                     <pip>
readline                  8.0                  h7b6447c_0  
scikit-learn              0.24.0                    <pip>
scipy                     1.6.0                     <pip>
setuptools                51.0.0           py37h06a4308_2  
six                       1.15.0           py37h06a4308_0  
sklearn                   0.0                       <pip>
sqlite                    3.33.0               h62c20be_0  
TensorDecomp              1.0                       <pip>
tensorly                  0.4.2                     <pip>
threadpoolctl             2.1.0                     <pip>
tk                        8.6.10               hbc83047_0  
torchvision               0.5.0                py37_cu101    pytorch
typing_extensions         3.7.4.3                    py_0  
wheel                     0.36.2             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
yacs                      0.1.8                     <pip>
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h9ceee32_0  
