MODEL:
    CKPT : "/scratch/16ee35016/HSDCNN/hsd_semantic/checkpoints/cifar100/vgg16/10/model-best-13-03.pth.tar"
    HSD_CKPT :  ""
DATASET:
    NAME : 'cifar100'
    NUM_CLASSES : 100
CLUSTER:
    NCLUST : 3
SOLVER:
    XE : True
    SEPARATE : True
    BASE_LR : 1e-3
HIERARCHY:
    BETA : 10

