MODEL:
    CKPT : "/scratch/16ee35016/HSDCNN/hsd_semantic/checkpoints/cifar10/vgg16/15/model-best-04-03.pth.tar"
    HSD_CKPT :  ""
DATASET:
    NAME : 'cifar10'
    NUM_CLASSES : 10
SOLVER:
    XE : False
HIERARCHY:
    BETA : 15

