MODEL:
    CKPT : "/scratch/16ee35016/HSDCNN/hsd_semantic/checkpoints/cifar10/vgg16/30/model-best-04-03.pth.tar"
    HSD_CKPT :  ""
DATASET:
    NAME : 'cifar10'
    NUM_CLASSES : 10
CLUSTER:
    NCLUST : 3
SOLVER:
    XE : True
    SEPARATE : True
    BASE_LR : 1e-3
HIERARCHY:
    BETA : 30

